version: '3.8'
services:
  nginx:
    image: nginx
    container_name: meli-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./service-config/nginx.conf:/etc/nginx/nginx.conf
      - nginx-data-volumen:/data/nginx/cache

    depends_on:
      - app
    networks: 
      - meli
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ./short-url-app
      dockerfile: Containerfile
    environment:
        APP_NAME: Meli Short Url
        API_VERSION: 1.0.0
        API_PORT: 8000
        DEBUG_MODE: true
        DATABASE_HOST: meli-postgres
        REDIS_HOST: meli-redis
        REDIS_PASSWORD: meli
        NATS_SERVER: nats://meli-nats:4222
        BASE_URL: https://74bb-200-113-133-203.ngrok-free.app # Only for ngrok
        URL_SIZE: 6
    depends_on:
      - nats
      - redis
      - postgres
    networks: 
      - meli
  events:
    container_name: events
    build:
      context: ./short-url-events
      dockerfile: Containerfile
    environment:
        APP_PORT: 8010
        DB_HOST: meli-postgres
        REDIS_HOST: meli-redis
        REDIS_PASSWORD: meli
        REDIS_RETRY_DELAY_MS: 3000
        REDIS_RETRY_ATTEMPS: 20
        DB_SYNC: false
        NATS_SERVERS: nats://meli-nats:4222
        URL_SHORT_URL_APP: http://short-url-app:8000
    depends_on:
      - nats
      - redis
    networks: 
      - meli
volumes:
  nginx-data-volumen:
    driver: local
networks:
  meli:
    name: meli