version: '3.8'
services:
  redis:
    image: redis:7.0.11-alpine
    container_name: meli-redis
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    command: redis-server /usr/local/etc/redis/redis.conf --save 20 1 --loglevel warning --requirepass meli
    networks:
      - meli
    volumes:
      - ./service-config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-volumen:/data
  # Postgres Server
  postgres:
    image: postgres:13
    container_name: meli-postgres
    environment:
      POSTGRES_USER: meli
      POSTGRES_PASSWORD: meli
      POSTGRES_DB: meli
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "meli", "-d", "meli"]
      interval: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - meli
  # Nats Server
  nats:
    container_name: meli-nats
    image: nats:latest
    command: "--jetstream --store_dir /data --http_port 8222"
    volumes:
      - nats1-data-volume:/data
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - meli
    healthcheck:
        test: echo $$(wget --server-response http://0.0.0.0:8222/varz 2>&1 | grep  '200 OK') | grep '200'  || exit 1
        interval: 20s
        timeout: 5s
        retries: 5
        start_period: 40s
  # pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: edwin@hola.ai
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data-volume:/var/lib/pgadmin
    networks:
      - meli
volumes:
  redis-data-volumen:
    driver: local
  postgres-data-volume:
    driver: local
  pgadmin-data-volume:
    driver: local
  nats1-data-volume:
    driver: local
networks:
  meli:
    name: meli